# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'COMPorts.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
import serial.tools.list_ports

ports = serial.tools.list_ports.comports()

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(550, 150)
        MainWindow.setMinimumSize(QtCore.QSize(550, 150))
        MainWindow.setMaximumSize(QtCore.QSize(550, 150))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(40, 30, 481, 21))
        self.comboBox.setObjectName("comboBox")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(350, 90, 171, 31))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        for port, desc, hwid in sorted(ports):
            self.comboBox.addItem("")
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
########################################################################################
        self.pushButton.clicked.connect(self.okay)
    def okay(self):
        a =str(self.comboBox.currentText())
        b = []
        for i in a:
            if i != ':':
                b.append(i)
            if i == ':':
                break
        with open('com.txt','w') as f:
            ab=''
            for i in b:
                ab += i
            f.write(ab)
        app.exit()
        os.startfile('Trend.exe')

########################################################################################
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "COM Ports"))
        isnumber = 0
        Port = []
        for port, desc, hwid in sorted(ports):
            Port.append(port)
            self.comboBox.setItemText(isnumber, _translate("MainWindow", "{}: {} [{}]".format(port, desc, hwid)))
            isnumber += 1
        self.pushButton.setText(_translate("MainWindow", "OK"))

app = QtWidgets.QApplication(sys.argv)
MainWindow = QtWidgets.QMainWindow()
ui = Ui_MainWindow()
ui.setupUi(MainWindow)
MainWindow.show()

sys.exit(app.exec_())


